# permissions for end users to edit invoices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: invoice-editor-role
rules:
- apiGroups:
  - facturnetes.cnvergence.io
  resources:
  - invoices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - facturnetes.cnvergence.io
  resources:
  - invoices/status
  verbs:
  - get
